sonar.projectKey=nestharus_ui-designer
sonar.organization=nestharus


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=ui-designer
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,plans/**,docs/**,AGENTS/**,**.md,**.lock,.changeset/**,.idea/**,**/.turbo/**,.vscode/**,.bun-cache/**,**/.next/**,**/coverage/**,**/storybook-static/**,**/out/**,.env*


# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
